#!/usr/bin/env python
#Author: Group 3 (BSIT-3A)
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OurGui.ui'
#
# Created: Tue Mar 15 20:44:30 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogMain(object):
    def setupUi(self, DialogMain):
        DialogMain.setObjectName(_fromUtf8("DialogMain"))
        DialogMain.resize(553, 260)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        DialogMain.setFont(font)
        self.gridLayout = QtGui.QGridLayout(DialogMain)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(DialogMain)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(DialogMain)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.StudlineEdit = QtGui.QLineEdit(DialogMain)
        self.StudlineEdit.setObjectName(_fromUtf8("StudlineEdit"))
        self.horizontalLayout.addWidget(self.StudlineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.AddpushButton = QtGui.QPushButton(DialogMain)
        self.AddpushButton.setObjectName(_fromUtf8("AddpushButton"))
        self.verticalLayout.addWidget(self.AddpushButton)
        self.DeletepushButton = QtGui.QPushButton(DialogMain)
        self.DeletepushButton.setObjectName(_fromUtf8("DeletepushButton"))
        self.verticalLayout.addWidget(self.DeletepushButton)
        self.NextpushButton = QtGui.QPushButton(DialogMain)
        self.NextpushButton.setObjectName(_fromUtf8("NextpushButton"))
        self.verticalLayout.addWidget(self.NextpushButton)
        self.PreviouspushButton = QtGui.QPushButton(DialogMain)
        self.PreviouspushButton.setObjectName(_fromUtf8("PreviouspushButton"))
        self.verticalLayout.addWidget(self.PreviouspushButton)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 4, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.FirstpushButton = QtGui.QPushButton(DialogMain)
        self.FirstpushButton.setObjectName(_fromUtf8("FirstpushButton"))
        self.verticalLayout_3.addWidget(self.FirstpushButton)
        self.LastpushButton = QtGui.QPushButton(DialogMain)
        self.LastpushButton.setObjectName(_fromUtf8("LastpushButton"))
        self.verticalLayout_3.addWidget(self.LastpushButton)
        self.UpdatepushButton = QtGui.QPushButton(DialogMain)
        self.UpdatepushButton.setObjectName(_fromUtf8("UpdatepushButton"))
        self.verticalLayout_3.addWidget(self.UpdatepushButton)
        self.EditpushButton = QtGui.QPushButton(DialogMain)
        self.EditpushButton.setObjectName(_fromUtf8("EditpushButton"))
        self.verticalLayout_3.addWidget(self.EditpushButton)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 4, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ClearpushButton = QtGui.QPushButton(DialogMain)
        self.ClearpushButton.setObjectName(_fromUtf8("ClearpushButton"))
        self.verticalLayout_4.addWidget(self.ClearpushButton)
        self.SearchpushButton = QtGui.QPushButton(DialogMain)
        self.SearchpushButton.setObjectName(_fromUtf8("SearchpushButton"))
        self.verticalLayout_4.addWidget(self.SearchpushButton)
        self.ClosepushButton = QtGui.QPushButton(DialogMain)
        self.ClosepushButton.setObjectName(_fromUtf8("ClosepushButton"))
        self.verticalLayout_4.addWidget(self.ClosepushButton)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 3, 3, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(DialogMain)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.FNlineEdit = QtGui.QLineEdit(DialogMain)
        self.FNlineEdit.setObjectName(_fromUtf8("FNlineEdit"))
        self.horizontalLayout_2.addWidget(self.FNlineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(DialogMain)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.LNlineEdit = QtGui.QLineEdit(DialogMain)
        self.LNlineEdit.setObjectName(_fromUtf8("LNlineEdit"))
        self.horizontalLayout_3.addWidget(self.LNlineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(DialogMain)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.CourselineEdit = QtGui.QLineEdit(DialogMain)
        self.CourselineEdit.setObjectName(_fromUtf8("CourselineEdit"))
        self.horizontalLayout_4.addWidget(self.CourselineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(DialogMain)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.YearlineEdit = QtGui.QLineEdit(DialogMain)
        self.YearlineEdit.setObjectName(_fromUtf8("YearlineEdit"))
        self.horizontalLayout_5.addWidget(self.YearlineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(DialogMain)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.StudlineEdit_2 = QtGui.QLineEdit(DialogMain)
        self.StudlineEdit_2.setObjectName(_fromUtf8("StudlineEdit_2"))
        self.horizontalLayout_6.addWidget(self.StudlineEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)

        self.retranslateUi(DialogMain)
        QtCore.QMetaObject.connectSlotsByName(DialogMain)

    def retranslateUi(self, DialogMain):
        DialogMain.setWindowTitle(_translate("DialogMain", "Dialog", None))
        self.label_7.setText(_translate("DialogMain", "<html><head/><body><p><span style=\" font-style:italic; color:#b30931;\">Student Information:</span></p></body></html>", None))
        self.label.setText(_translate("DialogMain", "<html><head/><body><p><span style=\" font-style:italic; color:#b30931;\">Student ID:</span></p></body></html>", None))
        self.AddpushButton.setText(_translate("DialogMain", "&Add", None))
        self.DeletepushButton.setText(_translate("DialogMain", "&Delete", None))
        self.NextpushButton.setText(_translate("DialogMain", "&Next", None))
        self.PreviouspushButton.setText(_translate("DialogMain", "Previous", None))
        self.FirstpushButton.setText(_translate("DialogMain", "&First", None))
        self.LastpushButton.setText(_translate("DialogMain", "&Last", None))
        self.UpdatepushButton.setText(_translate("DialogMain", "&Update", None))
        self.EditpushButton.setText(_translate("DialogMain", "&Edit", None))
        self.ClearpushButton.setText(_translate("DialogMain", "C&lear", None))
        self.SearchpushButton.setText(_translate("DialogMain", "&Search", None))
        self.ClosepushButton.setText(_translate("DialogMain", "&Close", None))
        self.label_2.setText(_translate("DialogMain", "<html><head/><body><p><span style=\" font-style:italic; color:#b30931;\">First Name:</span></p></body></html>", None))
        self.label_3.setText(_translate("DialogMain", "<html><head/><body><p><span style=\" font-style:italic; color:#b30931;\">Last Name:</span></p></body></html>", None))
        self.label_4.setText(_translate("DialogMain", "<html><head/><body><p><span style=\" font-style:italic; color:#b30931;\">Course:</span></p></body></html>", None))
        self.label_5.setText(_translate("DialogMain", "<html><head/><body><p><span style=\" font-style:italic; color:#b30931;\">Year:</span></p></body></html>", None))
        self.label_6.setText(_translate("DialogMain", "<html><head/><body><p><span style=\" font-style:italic; color:#b30931;\">Section:</span></p></body></html>", None))

